---
version: "2"

services:
  app:
    build: ./
    image: kafka-to-hbase:latest
    restart: on-failure
    depends_on:
      - kafka
      - hbase
    environment:
      K2HB_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      K2HB_KAFKA_SSL: "false"
      K2HB_KAFKA_GROUP_ID: "kafka-to-hbase-docker"
      K2HB_KAFKA_TOPICS: "docker,integration-test"
      K2HB_HBASE_HOST: "hbase"
      K2HB_HBASE_NAMESPACE: "k2hb"
      K2HB_HBASE_COLUMN: "cf:data"

  kafka:
    image: harisekhon/kafka:latest
    restart: on-failure
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOSTNAME: kafka

  hbase:
    image: harisekhon/hbase:latest
    restart: on-failure
    ports:
      - "9090:9090"
      - "9095:9095"

  python:
    image: kafka-to-hbase:latest
    entrypoint: "/usr/local/bin/python3"
    command: "--version"
    volumes:
      - ".:/app"
    working_dir: "/app"
    environment:
      K2HB_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      K2HB_KAFKA_SSL: "false"
      K2HB_HBASE_HOST: "hbase"

  integration-tests:
    image: integration-tests:latest
    build: ./integration_tests
    command: "--version"
    volumes:
      - "./integration_tests:/tests"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      HBASE_HOST: "hbase"
