---
version: "2.2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:4.1.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  hbase:
    image: hbase:latest
    build: ./docker/hbase
    environment:
      ZOOKEEPER_QUORUM: zookeeper
      HBASE_SCRIPT: |
        create_namespace "k2hb"
        create "k2hb:ingest", NAME => "topic", VERSIONS => 2147483647, MIN_VERSIONS => 1
        create "k2hb:ingest-topic", NAME => "c"

  kafka2hbase:
    image: kafka2hbase:latest
    build: ./
    depends_on:
      - kafka
      - hbase
    environment:
      K2HB_KAFKA_INSECURE: "true"

  integration-test:
    image: kafka2hbase-integration:latest
    build:
      dockerfile: integration.Dockerfile
      context: ./
    depends_on:
      - kafka2hbase
    command: "true"
    environment:
      SUID: ${UID-1000}
      SGID: ${GROUPS-1000}
      K2HB_KAFKA_INSECURE: "true"
