---
version: "2"

services:
  app:
    build: ./
    image: kafka-to-hbase:latest
    command: "true"
    depends_on:
      - kafka
      - hbase
    environment:
      K2HB_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      K2HB_KAFKA_SSL: "false"
      K2HB_HBASE_HOST: "hbase"

  kafka:
    image: harisekhon/kafka
    ports:
      - "2181:2181"
      - "9092:9092"

  hbase:
    image: harisekhon/hbase
    ports:
      - "9090:9090"
      - "9095:9095"
