version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: apt-get install -y build-essential python3-dev
      - run: python setup.py bdist_wheel
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: pip install .[dev]
      - run: nosetests
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
