version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo apt-get install -y build-essential python3-dev
      - run: python setup.py bdist_wheel
      - run: pip install --user dist/kafka_to_hbase-1.0-py3-none-any.whl[dev]
      - run: nosetests
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
